
ApplicationFrame.title = CARP VTT

BattleMapEditJInternalFrame.field.content.label = Content:
BattleMapEditJInternalFrame.field.name.label    = Name:
BattleMapEditJInternalFrame.title               = Bearbeiten: Battle Maps

EditorPanel.button.cancel.label = Abbruch
EditorPanel.button.delete.label = L\u00F6schen
EditorPanel.button.ok.label     = Ok

MainMenuBar.menu.edit.item.battleMaps.label = Battle Maps
MainMenuBar.menu.edit.item.tokens.label     = Tokens
MainMenuBar.menu.edit.label                 = Verwalten
MainMenuBar.menu.file.item.quit.label       = Beenden
MainMenuBar.menu.file.label                 = Datei
MainMenuBar.menu.map.label                  = Maps
MainMenuBar.menu.map.open.label             = \u00D6ffnen ...
MainMenuBar.menu.sync.label                 = Synchronisieren
MainMenuBar.menu.sync.battlemaps.label      = Battle Maps
MainMenuBar.menu.sync.tokens.label          = Tokens

TokenEditJInternalFrame.field.content.label   = Content:
TokenEditJInternalFrame.field.name.label      = Name:
TokenEditJInternalFrame.field.tokenSize.label = Tokengr\u00F6\u00DFe:
TokenEditJInternalFrame.title                 = Bearbeiten: Tokens

UploadComponent.button.browse.label = Suchen
