
ApplicationFrame.title = CARP VTT

EditorPanel.button.cancel.label = Abbruch
EditorPanel.button.delete.label = L\u00F6schen
EditorPanel.button.ok.label     = Ok

MainMenuBar.menu.edit.item.tokens.label = Tokens
MainMenuBar.menu.edit.label             = Verwalten
MainMenuBar.menu.file.item.quit.label   = Beenden
MainMenuBar.menu.file.label             = Datei
MainMenuBar.menu.map.label              = Maps
MainMenuBar.menu.map.open.label         = \u00D6ffnen ...

TokenEditJInternalFrame.field.content.label = Content:
TokenEditJInternalFrame.field.name.label    = Name:
TokenEditJInternalFrame.title               = Bearbeiten: Tokens

UploadComponent.button.browse.label = Suchen
