default-target-path: tmp
ucg-version: 1.0
properties:
  - name: baselib
    value: de.ollie.baselib
  - name: core-exception-package
    value: de.ollie.carp.vtt.restserver.core.service.exception
  - name: core-model-package
    value: de.ollie.carp.vtt.restserver.core.service.model
  - name: core-port-persistence-package
    value: de.ollie.carp.vtt.restserver.core.service.port.persistence
  - name: core-service-package
    value: de.ollie.carp.vtt.restserver.core.service
  - name: jpa-entity-package
    value: de.ollie.carp.vtt.restserver.persistence.jpa.dbo
  - name: jpa-mapper-package
    value: de.ollie.carp.vtt.restserver.persistence.jpa.mapper
  - name: jpa-repository-package
    value: de.ollie.carp.vtt.restserver.persistence.jpa.repository
generators:
# --- Service ---
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.core.service.model
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/core/Model.vc
    properties:
      - name: target-path
        value: src/main/java
      - name: suppress-project-type-imports
        value: true
  - type: ENUM
    package: de.ollie.carp.vtt.restserver.core.service.model
    suppress-when: classModel Load suppress-service HasProperty
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    template: templates/core/Enum.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.core.service.port.persistence
    suppress-when: classModel Load suppress-service HasProperty
    target-file-name: ${UnitName}PersistencePort
    path: ../generator
    template: templates/core/PersistencePort.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.core.service
    path: ../generator
    target-file-name: ${UnitName}Service
    template: templates/core/Service.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.core.service.impl
    target-file-name: ${UnitName}ServiceImpl
    path: ../generator
    template: templates/core/ServiceImpl.vc
    properties:
      - name: target-path
        value: src/main/java
# --- JPA ---
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.persistence.jpa.dbo
    suppress-when: classModel Load suppress-persistence HasProperty
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}Dbo
    template: templates/persistence/jpa/Dbo.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: ENUM
    package: de.ollie.carp.vtt.restserver.persistence.jpa.dbo
    suppress-when: classModel Load suppress-persistence HasProperty
    resource-class-loader: org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
    target-file-name: ${UnitName}Dbo
    template: templates/persistence/jpa/EnumDbo.vc
    properties:
      - name: target-path
        value: rest-server/src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.persistence.jpa.mapper
    suppress-when: classModel Load suppress-persistence HasProperty
    path: ../generator
    target-file-name: ${UnitName}DboMapper
    template: templates/jpa/DboMapper.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.persistence.jpa.repository
    suppress-when: classModel Load suppress-persistence HasProperty
    target-file-name: ${UnitName}DboRepository
    path: ../generator
    template: templates/jpa/DboRepository.vc
    properties:
      - name: target-path
        value: src/main/java
  - type: CLASS
    package: de.ollie.carp.vtt.restserver.persistence.jpa
    suppress-when: classModel Load suppress-persistence HasProperty
    target-file-name: ${UnitName}PersistenceJpaAdapter
    path: ../generator
    template: templates/jpa/PersistenceAdapter.vc
    properties:
      - name: target-path
        value: src/main/java
