@startuml


actor GAMEMASTER as "User\n(GM)"
actor PLAYER as "User\n(Player)"

component DesktopGM as "Gamemaster Application" {

    component DTGM as "CARP-VTT\n(Desktop)"

    database DBLC as "Database\n(Local)"

    DTGM -R-> DBLC : "JDBC\n(r/w)"

}

interface WSREST as "REST"

component Web as "Web Application" {

    component WGUI as "CARP-VTT\n(Web-GUI)"
    component WS as "CARP-VTT\n(Web-Service)"

    database DBWB as "Database\n(Web)"

    WS -D-> DBWB : "JDBC\n(r/w)"
    WGUI -U-> DBWB : "JDBC\n(r)"

    WS -U- WSREST

}

component DesktopPlayer as "Player Application" {

    component DTP as "CARP-VTT\n(Desktop)"

}

GAMEMASTER --> DTGM : "GUI\n(Richt Client)"

PLAYER -L-> WGUI : "GUI\n(Browser)"
PLAYER -U-> DTP : "GUI\n(Richt Client)"

DTP -L-( WSREST : "HTTP                "

DTGM -D-( WSREST : "HTTP"


@enduml