@startuml


actor GAMEMASTER as "User\n(GM)"
actor PLAYER as "User\n(Player)"

component DesktopGM as "Gamemaster Application" {

    component DTGM as "CARP-VTT-SWING\n(Desktop)"

    database DBLC as "Database\n(Local)"

    DTGM -R-> DBLC : "JDBC\n(r/w)"

}

interface WSREST as "REST"

component Rest as "Rest-Server" {

    component WS as "CARP-VTT-REST-SERVER"

    database DBWB as "Database\n(Web)"

    WS -D-> DBWB : "JDBC\n(r/w)"

    WS -U- WSREST

}

component DesktopPlayer as "Web Application" {

    component CVW as "CARP-VTT-WEB"

}

GAMEMASTER --> DTGM : "GUI\n(Richt Client)"

PLAYER -U-> CVW : "GUI\n(Browser)"

CVW -L-( WSREST : "HTTP                "

DTGM -D-( WSREST : "HTTP"


@enduml